name: build binaries

on:
  push:
    tags:
      - "c*"

jobs:
  build_matrix:
    strategy:
      matrix:
        env: [linux, windows, macos]
        include:
          - env: linux
            os: ubuntu-latest
            bin: twitchTransFN
            opts:
            archive: tar.gz
          - env: windows
            os: windows-latest
            bin: twitchTransFN.exe
            opts: --hidden-import=pywin32
            archive: zip
          - env: macos
            os: macos-latest
            bin: twitchTransFN.command
            opts: --hidden-import=AppKit
            archive: tar.gz
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        with: { python-version: 3.9 }

      - name: Upgrade PIP
        run: pip install --upgrade pip

      - name: Install DevTools
        if: ${{ matrix.env == 'macos' }}
        run: dnf -y groupinstall 'Development Tools'

      - name: install pyinstaller
        run: python -m pip install --upgrade pip PyInstaller

      - name: install requirements
        run: python -m pip install -r requirements.txt

      - name: remove config.py
        run: rm config.py

      - name: build
        run: pyinstaller ${{ matrix.opts }} --runtime-tmpdir="." --icon question.ico --exclude-module="config" --name ${{ matrix.bin }} -F ttfn_custom.py

      - name: archive with zip
        if: ${{ matrix.archive == 'zip' }}
        run: powershell Compress-Archive -Path dist/${{ matrix.bin }} -DestinationPath ${{ matrix.env }}.zip

      - name: archive with tar.gz
        if: ${{ matrix.archive == 'tar.gz' }}
        run: tar -C dist -pczvf ${{ matrix.env }}.tar.gz ${{ matrix.bin }}

      - name: update github release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          prerelease: false
          files: ${{ matrix.env }}.${{ matrix.archive }}
